apiVersion: v1
kind: Service
metadata:
  labels:
    app: core
    release: webhook
    component: mcm-webhook
    app.kubernetes.io/instance: webhook
    app.kubernetes.io/name: core
  name: webhook-core-webhook-service
spec:
  ports:
    - port: 443
      targetPort: 8000
  selector:
    app: core
    release: webhook
    component: mcm-webhook

