apiVersion: operators.open-cluster-management.io/v1alpha1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: default
spec:
  version: latest
  imageRepository: "quay.io/open-cluster-management"
  imageTagSuffix: ""
  imagePullPolicy: Always
  imagePullSecret: quay-secret
