apiVersion: operators.open-cluster-management.io/v1alpha1
kind: MultiClusterHub
metadata:
  name: example-multiclusterhub
  namespace: default
spec:
  version: latest
  imageRepository: "quay.io/open-cluster-management"
  imageTagSuffix: "SNAPSHOT-2020-04-03-15-10-14"
  imagePullPolicy: Always
  imagePullSecret: quay-secret
  cloudPakCompatibility: true
