apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: multiclusterhub-operator
rules:
- apiGroups:
  - ""
  - "admissionregistration.k8s.io"
  - "apiextensions.k8s.io"
  - "apiregistration.k8s.io"
  - "apps"
  - "apps.open-cluster-management.io"
  - "authorization.k8s.io"
  - "etcd.database.coreos.com"
  - "hive.openshift.io"
  - "mcm.ibm.com"
  - "rbac.authorization.k8s.io"
  - "security.openshift.io"
  resources:
  - apiservices
  - channels
  - clusterjoinrequests
  - clusterrolebindings
  - configmaps
  - customresourcedefinitions
  - deployments
  - etcdclusters
  - hiveconfigs
  - mutatingwebhookconfigurations
  - namespaces
  - pods
  - replicasets
  - rolebindings
  - secrets
  - securitycontextconstraints
  - serviceaccounts
  - services
  - subjectaccessreviews
  - subscriptions
  verbs:
  - get

- apiGroups:
  - ""
  - "admissionregistration.k8s.io"
  - "apiextensions.k8s.io"
  - "apiregistration.k8s.io"
  - "apps"
  - "apps.open-cluster-management.io"
  - "authorization.k8s.io"
  - "etcd.database.coreos.com"
  - "hive.openshift.io"
  - "monitoring.coreos.com"
  - "rbac.authorization.k8s.io"
  - "mcm.ibm.com"
  - "security.openshift.io"
  resources:
  - apiservices
  - channels
  - clusterjoinrequests
  - clusterrolebindings
  - clusterroles
  - configmaps
  - customresourcedefinitions
  - deployments
  - etcdclusters
  - hiveconfigs
  - mutatingwebhookconfigurations
  - namespaces
  - rolebindings
  - secrets
  - securitycontextconstraints
  - serviceaccounts
  - services
  - servicemonitors
  - subjectaccessreviews
  - subscriptions
  - validatingwebhookconfigurations
  verbs:
  - create

- apiGroups:
  - ""
  - "apps"
  - "admissionregistration.k8s.io"
  - "apiregistration.k8s.io"
  - "authorization.k8s.io"
  - "config.openshift.io"
  - "mcm.ibm.com"
  - "operators.open-cluster-management.io"
  - "rbac.authorization.k8s.io"
  resources:
  - apiservices
  - clusterjoinrequests
  - configmaps
  - deployments
  - ingresses
  - multiclusterhubs
  - namespaces
  - rolebindings
  - servicemonitors
  - secrets
  - services
  - subjectaccessreviews
  - validatingwebhookconfigurations
  verbs:
  - list

- apiGroups:
  - ""
  - "admissionregistration.k8s.io"
  - "apiregistration.k8s.io"
  - "apps"
  - "authorization.k8s.io"
  - "config.openshift.io"
  - "mcm.ibm.com"
  - "operators.open-cluster-management.io"
  - "rbac.authorization.k8s.io"
  - "storage.k8s.io"
  resources:
  - apiservices
  - configmaps
  - clusterjoinrequests
  - deployments
  - ingresses
  - multiclusterhubs
  - namespaces
  - rolebindings
  - secrets
  - services
  - storageclasses
  - subjectaccessreviews
  - validatingwebhookconfigurations
  verbs:
  - watch

- apiGroups:
  - ""
  - "admissionregistration.k8s.io"
  - "apps"
  - "mcm.ibm.com"
  - "monitoring.coreos.com"
  - "operators.open-cluster-management.io"
  resources:
  - deployments/finalizers
  - services
  - services/finalizers
  - servicemonitors
  - servicemonitors/finalizers
  - validatingwebhookconfigurations
  - multiclusterhubs
  - multiclusterhubs/finalizers
  - multiclusterhubs/status
  verbs:
  - update

- apiGroups:
  - "admissionregistration.k8s.io"
  - "apiextensions.k8s.io"
  - "apiregistration.k8s.io"
  - "hive.openshift.io"
  - "mcm.ibm.com"
  - "rbac.authorization.k8s.io"
  resources:
  - apiservices
  - clusterroles
  - clusterrolebindings
  - customresourcedefinitions
  - hiveconfigs
  - mutatingwebhookconfigurations
  verbs:
  - deletecollection
  
# RCM Dependancies
- apiGroups:
  - "agent.open-cluster-management.io"
  - "app.k8s.io"
  - "apps.open-cluster-management.io"
  - "clusterregistry.k8s.io"
  - "config.openshift.io"
  - "hive.openshift.io"
  - "mcm.ibm.com"
  - "multicloud.ibm.com"
  - "policy.mcm.ibm.com"
  resources:
  - applications
  - applications/status
  - applicationrelationships
  - applicationrelationships/status
  - channels
  - channels/status
  - clusterdeployments
  - clusters
  - clusters/status
  - clusterstatuses
  - clusterversions
  - deployables
  - deployables/status
  - deployableoverrides
  - deployableoverrides/status
  - endpointconfigs
  - helmrepos
  - helmrepos/status
  - klusterletconfigs
  - machinepools
  - placementbindings
  - placementpolicies
  - placementpolicies/status
  - placementrules
  - placementrules/status
  - policies
  - resourceviews
  - resourceviews/status
  - subscriptions
  - subscriptions/status
  - works
  - works/status
  - worksets
  - worksets/status
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
  - deletecollection
  - patch