kind: Deployment
apiVersion: apps/v1
metadata:
  name: connection-manager-deployment
  labels:
    app: core
    app.kubernetes.io/name: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
      component: "mcm-operator"
  template:
    metadata:
      labels:
        app: core
        component: "mcm-operator"
        app.kubernetes.io/name: core
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      serviceAccountName: hub-sa
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - mcm-operator
              topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
      - name: mcm-operator
        image: mcm-operator:3.3.0
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 25m
            memory: 128Mi    
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        args:
          - "/server-operator"
          - "--operator-configmap=default/release-name-core-operator-config"
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 15

