kind: Deployment
apiVersion: apps/v1
metadata:
  name: mcm-topology-aggregator
  labels:
    app: mcm-topology-aggregator
spec:
  selector:
    matchLabels:
      app: mcm-topology-aggregator
  template:
    metadata:
      labels:
        app: mcm-topology-aggregator
    spec:
      serviceAccountName: hub-sa
      containers:
        - name: mcm-topology-aggregator
          image: mcm-topology-aggregator
          env: []
          ports:
            - containerPort: 4000
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livenessProbe
              port: 4000
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readinessProbe
              port: 4000
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - name: tmp
              mountPath: "/tmp"
          args:
            - "/topology-aggregator"
            - "--mongo-database=mcm"
      volumes:
        - name: tmp
          emptyDir: {}
