apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: hub-sa-clusterrole
rules:
- apiGroups:
  - ""
  - "authorization.k8s.io"
  - "rbac.authorization.k8s.io"
  resources:
  - configmaps
  - namespaces
  - secrets
  - subjectaccessreviews
  - rolebindings
  verbs:
  - create
  - get
  - list
  - watch