apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: "{{ .sub.Name }}-sub"
  namespace: "{{ .sub.Namespace }}"
spec:
  channel: "{{ .mch.Namespace }}/{{ .channelName }}"
  packageOverrides:
  - packageName: {{ .sub.Name }}
    packageOverrides:
    - path: spec
      values: 
        {{ range $k, $v := $.sub.Overrides -}}
          {{- if isMap $v -}}
            {{ $k }}: 
            {{ range $k, $v := $v -}}
              {{- if isMap $v -}}
                {{ $k }}: 
                {{ range $k, $v := $v -}}
                  {{ $k }}: {{ $v }}
                {{ end -}}
              {{- end -}}
            {{- end -}}
          {{- end -}}
        {{ end }}