resources:
- rbac
- apiserver
- controller
- etcd
- mongodb
- webhook
- cluster_controller
- certificates
- topology_aggregator
- hive
- nginx
- channel
- repo
- management_ingress
# - connection_manager